# Generated by Django 4.0.3 on 2022-03-18 10:28
from django.db import migrations


def quiz_namer(apps, schema_editor):
    quiz = apps.get_model('quizlet', 'Quiz')
    names = ["Мемы", "Боги", "Оружие", "Биология", "Наука", "Актеры"]
    quiz.objects.bulk_create([(quiz(quiz_name=name)) for name in names])


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0002_alter_answer_question_alter_category_quiz_and_more'),
    ]

    operations = [
        migrations.RunPython(quiz_namer),
    ]
