# Generated by Django 4.0.3 on 2022-03-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0003_auto_20220318_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_quizzes', to='quizlet.category', verbose_name='ID категории'),
        ),
    ]
