# Generated by Django 4.0.3 on 2022-03-22 11:44

from django.db import migrations
from django.db.models import OuterRef, Subquery
from django.db.models.functions import Coalesce


def quiz_filler(apps, schema_editor):
    quiz_model = apps.get_model('quizlet', 'Quiz')
    category_model = apps.get_model('quizlet', 'Category')

    categories = category_model.objects.all()
    quizzes = quiz_model.objects.all()

    subquery = categories.filter(quiz_id=OuterRef('pk'))
    quizzes.update(category_id=Coalesce(Subquery(subquery.values('pk')[:1]), 1))


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0004_remove_category_quiz_remove_question_category_and_more'),
    ]

    operations = [
        migrations.RunPython(quiz_filler, migrations.RunPython.noop),
    ]
