# Generated by Django 4.0.3 on 2022-03-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0005_auto_20220322_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
