# Generated by Django 4.0.3 on 2022-03-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0006_remove_category_quiz_remove_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_annotation', to='quizlet.quiz', verbose_name='Аннотация опроса')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_annotation', to='quizlet.question', verbose_name='Аннотация вопроса')),
            ],
        ),
    ]
