# Generated by Django 4.0.3 on 2022-03-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0008_answer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizannotation',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuestionAnnotation',
        ),
        migrations.DeleteModel(
            name='QuizAnnotation',
        ),
    ]
