# Generated by Django 4.0.3 on 2022-04-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizlet', '0010_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
