# Generated by Django 4.0.3 on 2022-04-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0012_alter_useranswers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='answered_correct',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='count_correct',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='quiz',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='quizlet.question', verbose_name='ID опроса'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer',
            field=models.CharField(max_length=250, verbose_name='Ответ'),
        ),
    ]
