# Generated by Django 4.0.3 on 2022-04-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0013_remove_useranswers_answered_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizlet.answer', verbose_name='Ответ'),
        ),
    ]
